version: "3.7"
services:
  back:
    depends_on:
      - api
    build:
      context: hseling_web_wikingrams/
      
      dockerfile: Dockerfile
    ports:
      - "8000:80"

    command: ["python3", "manage.py", "runserver", "0.0.0.0:80"]

  api:
    build:
      context: hseling_api_wikingrams/
      dockerfile: Dockerfile
    ports:
      - "5000:80"

    command: [ "python3", "app.py" ]
